# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BBQMeetup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BBQMeetup

pod 'Firebase/Auth'
pod 'Firebase/Firestore'


  target 'BBQMeetupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
